# Generated by Django 4.2.2 on 2025-11-19 01:53

from django.db import migrations


def populate_activity_types(apps, schema_editor):
    ActivityType = apps.get_model('main', 'ActivityType')
    activities = ['Cycling', 'Hiking', 'Running', 'Walking']
    for activity in activities:
        ActivityType.objects.create(name=activity)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_activity_types),
    ]
